[2025-03-17 19:50:27,261] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 19:57:13,581] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 19:57:15,038] ERROR in app: Falha ao carregar modelo de difusão: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install 'accelerate>=0.26.0'`
[2025-03-17 19:57:15,055] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 19:57:15,055] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 19:57:15,055] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 19:57:15,061] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 19:57:15,061] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 20:01:27,352] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 20:01:28,894] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 20:01:28,900] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 20:01:28,900] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 20:01:28,901] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 20:01:28,905] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 20:01:28,905] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:00:11,268] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:00:13,209] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:00:13,218] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:00:13,218] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:00:13,218] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:00:13,223] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:00:13,223] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:00:53,152] INFO in app: [GEN] Indexacao/treino gerativo com as dirs = ['/home/marco-alecsander/Scrivania/STUDIO ELLE RGB (JPG)']
[2025-03-17 21:35:51,950] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:35:54,491] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:35:54,508] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:35:54,508] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:35:54,508] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:35:54,514] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:35:54,514] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:47:17,552] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:47:19,117] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:47:19,125] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:47:19,125] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:47:19,125] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:47:19,129] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:47:19,130] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:50:35,735] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:50:38,765] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:50:38,772] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:50:38,772] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:50:38,772] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:50:38,778] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:50:38,778] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:51:42,621] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:51:44,237] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:51:44,246] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:51:44,246] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:51:44,246] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:51:44,252] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:51:44,252] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:51:53,904] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742244713
[2025-03-17 21:53:38,916] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:53:40,754] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:53:40,767] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:53:40,768] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:53:40,768] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:53:40,775] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:53:40,775] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:54:14,120] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:54:15,815] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:54:15,822] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:54:15,822] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:54:15,822] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:54:15,827] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:54:15,827] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:54:23,295] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742244863
[2025-03-17 21:54:54,023] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:54:55,927] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:54:55,937] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:54:55,937] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:54:55,937] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:54:55,943] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:54:55,943] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:55:00,352] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742244900
[2025-03-17 21:55:10,649] INFO in app: [TREINO_LORA] Executando: accelerate launch train_lora.py --pretrained_model_name=runwayml/stable-diffusion-v1-5 --train_data_dir=/tmp/train_lora_dataset_1742244900 --output_dir=./lora_output_kvzxdo --instance_prompt=fabricStyle --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1000 --revision=fp16
[2025-03-17 21:55:20,810] INFO in app: Saída train_lora.py:

[2025-03-17 21:55:20,811] ERROR in app: Falha no treino LoRA: The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `0`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.6.0+cpu)
    Python  3.12.9 (you have 3.12.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2025-03-17 21:55:19,189 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: no

2025-03-17 21:55:19,196 - INFO - __main__ - Criando dataset...
2025-03-17 21:55:19,246 - INFO - __main__ - Carregando pipeline base: runwayml/stable-diffusion-v1-5
/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/resolve/fp16/model_index.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/diffusers/configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1295, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 383, in _request_wrapper
    return _request_wrapper(method=method, url=next_url, follow_relative_redirects=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 388, in _request_wrapper
    hf_raise_for_status(response)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 413, in hf_raise_for_status
    raise _format(RevisionNotFoundError, message, response) from e
huggingface_hub.errors.RevisionNotFoundError: 404 Client Error. (Request ID: Root=1-67d88c37-56209b022311b8b241bccf1c;37f64d9f-0044-43c5-ae74-afc95e1b4eec)

Revision Not Found for url: https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/resolve/fp16/model_index.json.
Invalid rev id: fp16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 392, in <module>
    main()
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 388, in main
    train_loop(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 292, in train_loop
    pipe, unet, vae, text_encoder, tokenizer = create_model(args, accelerator)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 192, in create_model
    pipe = DiffusionPipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 589, in from_pretrained
    config_dict = cls.load_config(
                  ^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/diffusers/configuration_utils.py", line 348, in load_config
    raise EnvironmentError(
OSError: fp16 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/runwayml/stable-diffusion-v1-5' for available revisions.
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1194, in launch_command
    simple_launcher(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 780, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/python', 'train_lora.py', '--pretrained_model_name=runwayml/stable-diffusion-v1-5', '--train_data_dir=/tmp/train_lora_dataset_1742244900', '--output_dir=./lora_output_kvzxdo', '--instance_prompt=fabricStyle', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000', '--revision=fp16']' returned non-zero exit status 1.

[2025-03-17 21:57:25,604] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 21:57:27,629] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 21:57:27,637] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 21:57:27,637] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 21:57:27,637] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 21:57:27,642] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 21:57:27,642] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 21:57:32,226] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742245052
[2025-03-17 21:57:49,122] INFO in app: [TREINO_LORA] Executando: accelerate launch train_lora.py --pretrained_model_name=runwayml/stable-diffusion-v1-5 --train_data_dir=/tmp/train_lora_dataset_1742245052 --output_dir=./lora_output_acbeoc --instance_prompt=fabricStyle --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1000
[2025-03-17 21:58:00,469] INFO in app: Saída train_lora.py:

[2025-03-17 21:58:00,470] ERROR in app: Falha no treino LoRA: The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `0`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.6.0+cpu)
    Python  3.12.9 (you have 3.12.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2025-03-17 21:57:55,491 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: no

2025-03-17 21:57:55,493 - INFO - __main__ - Criando dataset...
2025-03-17 21:57:55,539 - INFO - __main__ - Carregando pipeline base: runwayml/stable-diffusion-v1-5
/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]
Fetching 15 files: 100%|██████████| 15/15 [00:00<00:00, 170039.35it/s]
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 392, in <module>
    main()
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 388, in main
    train_loop(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 292, in train_loop
    pipe, unet, vae, text_encoder, tokenizer = create_model(args, accelerator)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 215, in create_model
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 864, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 1038, in from_pretrained
    raise ValueError(
ValueError: Unrecognized model in runwayml/stable-diffusion-v1-5. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, bros, camembert, canine, chameleon, chinese_clip, chinese_clip_vision_model, clap, clip, clip_text_model, clip_vision_model, clipseg, clvp, code_llama, codegen, cohere, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, dac, data2vec-audio, data2vec-text, data2vec-vision, dbrx, deberta, deberta-v2, decision_transformer, deformable_detr, deit, depth_anything, deta, detr, dinat, dinov2, distilbert, donut-swin, dpr, dpt, efficientformer, efficientnet, electra, encodec, encoder-decoder, ernie, ernie_m, esm, falcon, falcon_mamba, fastspeech2_conformer, flaubert, flava, fnet, focalnet, fsmt, funnel, fuyu, gemma, gemma2, git, glpn, gpt-sw3, gpt2, gpt_bigcode, gpt_neo, gpt_neox, gpt_neox_japanese, gptj, gptsan-japanese, granite, granitemoe, graphormer, grounding-dino, groupvit, hiera, hubert, ibert, idefics, idefics2, imagegpt, informer, instructblip, instructblipvideo, jamba, jetmoe, jukebox, kosmos-2, layoutlm, layoutlmv2, layoutlmv3, led, levit, lilt, llama, llava, llava_next, llava_next_video, llava_onevision, longformer, longt5, luke, lxmert, m2m_100, mamba, mamba2, marian, markuplm, mask2former, maskformer, maskformer-swin, mbart, mctct, mega, megatron-bert, mgp-str, mimi, mistral, mixtral, mllama, mobilebert, mobilenet_v1, mobilenet_v2, mobilevit, mobilevitv2, mpnet, mpt, mra, mt5, musicgen, musicgen_melody, mvp, nat, nemotron, nezha, nllb-moe, nougat, nystromformer, olmo, olmoe, omdet-turbo, oneformer, open-llama, openai-gpt, opt, owlv2, owlvit, paligemma, patchtsmixer, patchtst, pegasus, pegasus_x, perceiver, persimmon, phi, phi3, pix2struct, pixtral, plbart, poolformer, pop2piano, prophetnet, pvt, pvt_v2, qdqbert, qwen2, qwen2_audio, qwen2_audio_encoder, qwen2_moe, qwen2_vl, rag, realm, recurrent_gemma, reformer, regnet, rembert, resnet, retribert, roberta, roberta-prelayernorm, roc_bert, roformer, rt_detr, rt_detr_resnet, rwkv, sam, seamless_m4t, seamless_m4t_v2, segformer, seggpt, sew, sew-d, siglip, siglip_vision_model, speech-encoder-decoder, speech_to_text, speech_to_text_2, speecht5, splinter, squeezebert, stablelm, starcoder2, superpoint, swiftformer, swin, swin2sr, swinv2, switch_transformers, t5, table-transformer, tapas, time_series_transformer, timesformer, timm_backbone, trajectory_transformer, transfo-xl, trocr, tvlt, tvp, udop, umt5, unispeech, unispeech-sat, univnet, upernet, van, video_llava, videomae, vilt, vipllava, vision-encoder-decoder, vision-text-dual-encoder, visual_bert, vit, vit_hybrid, vit_mae, vit_msn, vitdet, vitmatte, vits, vivit, wav2vec2, wav2vec2-bert, wav2vec2-conformer, wavlm, whisper, xclip, xglm, xlm, xlm-prophetnet, xlm-roberta, xlm-roberta-xl, xlnet, xmod, yolos, yoso, zoedepth
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1194, in launch_command
    simple_launcher(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 780, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/python', 'train_lora.py', '--pretrained_model_name=runwayml/stable-diffusion-v1-5', '--train_data_dir=/tmp/train_lora_dataset_1742245052', '--output_dir=./lora_output_acbeoc', '--instance_prompt=fabricStyle', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.

[2025-03-17 22:01:58,238] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 22:02:00,000] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 22:02:00,009] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 22:02:00,009] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 22:02:00,009] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 22:02:00,013] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 22:02:00,013] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 22:02:07,190] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742245327
[2025-03-17 22:02:15,552] INFO in app: [TREINO_LORA] Executando: accelerate launch train_lora.py --pretrained_model_name=runwayml/stable-diffusion-v1-5 --train_data_dir=/tmp/train_lora_dataset_1742245327 --output_dir=./lora_output_tywtfi --instance_prompt=fabricStyle --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1000
[2025-03-17 22:02:24,969] INFO in app: Saída train_lora.py:

[2025-03-17 22:02:24,969] ERROR in app: Falha no treino LoRA: The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `0`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.6.0+cpu)
    Python  3.12.9 (you have 3.12.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2025-03-17 22:02:21,901 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: no

2025-03-17 22:02:21,903 - INFO - __main__ - Criando dataset...
2025-03-17 22:02:21,946 - INFO - __main__ - Carregando pipeline base: runwayml/stable-diffusion-v1-5
/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]
Fetching 15 files: 100%|██████████| 15/15 [00:00<00:00, 146653.99it/s]
2025-03-17 22:02:23,990 - INFO - __main__ - Total de parâmetros LOARA = 0
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 398, in <module>
    main()
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 394, in main
    train_loop(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 311, in train_loop
    optimizer = torch.optim.AdamW(
                ^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/torch/optim/adamw.py", line 100, in __init__
    super().__init__(params, defaults)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 372, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1194, in launch_command
    simple_launcher(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 780, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/python', 'train_lora.py', '--pretrained_model_name=runwayml/stable-diffusion-v1-5', '--train_data_dir=/tmp/train_lora_dataset_1742245327', '--output_dir=./lora_output_tywtfi', '--instance_prompt=fabricStyle', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.

[2025-03-17 22:04:04,212] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 22:04:05,519] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 22:04:05,526] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 22:04:05,526] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 22:04:05,527] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 22:04:05,531] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 22:04:05,531] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 22:04:11,213] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742245451
[2025-03-17 22:04:19,224] INFO in app: [TREINO_LORA] Executando: accelerate launch train_lora.py --pretrained_model_name=runwayml/stable-diffusion-v1-5 --train_data_dir=/tmp/train_lora_dataset_1742245451 --output_dir=./lora_output_cjkmps --instance_prompt=fabricStyle --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1000
[2025-03-17 22:04:28,516] INFO in app: Saída train_lora.py:

[2025-03-17 22:04:28,516] ERROR in app: Falha no treino LoRA: The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `0`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.6.0+cu124 with CUDA 1204 (you have 2.6.0+cpu)
    Python  3.12.9 (you have 3.12.3)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2025-03-17 22:04:25,977 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: no

2025-03-17 22:04:25,978 - INFO - __main__ - Criando dataset...
2025-03-17 22:04:26,025 - INFO - __main__ - Carregando pipeline base: runwayml/stable-diffusion-v1-5

Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]
Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:00, 16.54it/s]
Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00,  9.03it/s]
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 11.04it/s]
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00, 10.99it/s]
2025-03-17 22:04:27,472 - INFO - __main__ - Total de parâmetros LOARA = 0
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 398, in <module>
    main()
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 394, in main
    train_loop(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/train_lora.py", line 311, in train_loop
    optimizer = torch.optim.AdamW(
                ^^^^^^^^^^^^^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/torch/optim/adamw.py", line 100, in __init__
    super().__init__(params, defaults)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 372, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
Traceback (most recent call last):
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1194, in launch_command
    simple_launcher(args)
  File "/home/marco-alecsander/PycharmProjects/ByteAI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 780, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marco-alecsander/PycharmProjects/ByteAI/.venv/bin/python', 'train_lora.py', '--pretrained_model_name=runwayml/stable-diffusion-v1-5', '--train_data_dir=/tmp/train_lora_dataset_1742245451', '--output_dir=./lora_output_cjkmps', '--instance_prompt=fabricStyle', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.

[2025-03-17 22:08:17,254] INFO in app: Carregando modelo Stable Diffusion (v1-5) para geração de imagens...
[2025-03-17 22:08:18,797] INFO in app: Modelo carregado com sucesso! Usando device=cpu.
[2025-03-17 22:08:18,806] DEBUG in app: [DEBUG] __main__ -> Chamando start_scheduler() para APScheduler.
[2025-03-17 22:08:18,806] DEBUG in app: start_scheduler() chamado. Carregando pianificazione...
[2025-03-17 22:08:18,806] DEBUG in app: Programando reindex com day_of_week=mon,tue,wed,thu,fri,sat,sun, hour=22, minute=21
[2025-03-17 22:08:18,810] DEBUG in app: APScheduler iniciado. Jobs atuais: [<Job (id=reindex_agendado name=job_reindicizza_programmata)>]
[2025-03-17 22:08:18,810] DEBUG in app: [DEBUG] Subindo waitress server na porta 5000...
[2025-03-17 22:08:39,646] INFO in app: Treino LoRA - Pasta temporária: /tmp/train_lora_dataset_1742245719
[2025-03-17 22:08:48,150] INFO in app: [TREINO_LORA] Executando: accelerate launch train_lora.py --pretrained_model_name=runwayml/stable-diffusion-v1-5 --train_data_dir=/tmp/train_lora_dataset_1742245719 --output_dir=./lora_output_mllgny --instance_prompt=fabricStyle --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_scheduler=constant --lr_warmup_steps=0 --max_train_steps=1000
